// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIdaP9AhMvdEtDrCW_3-gRjQP2sRwFSzA',
    appId: '1:780860116306:web:0236cbea7b8c2921927e8b',
    messagingSenderId: '780860116306',
    projectId: 'lozcam-movil',
    authDomain: 'lozcam-movil.firebaseapp.com',
    storageBucket: 'lozcam-movil.firebasestorage.app',
    measurementId: 'G-Z4P67YMNWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRbBbo_Pxsk-HdCzXZi5S9Gemru-e-Neg',
    appId: '1:780860116306:android:5288c4d9ef5c5c03927e8b',
    messagingSenderId: '780860116306',
    projectId: 'lozcam-movil',
    storageBucket: 'lozcam-movil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDPFsRNg2FWyzKBERu8kQqPWhDjy4LXkc',
    appId: '1:780860116306:ios:14ac565d2b34b3cc927e8b',
    messagingSenderId: '780860116306',
    projectId: 'lozcam-movil',
    storageBucket: 'lozcam-movil.firebasestorage.app',
    iosBundleId: 'pe.lozcam.lozcamMovil',
  );
}
